# Generated by Django 5.0.3 on 2024-04-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BankUser',
        ),
    ]
