import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={[
          `${inter.className}`,
          " grid min-h-full grid-rows-12 grid-cols-12",
        ].join("")}
      >
        <header className="bg-emerald-500 p-3 row-start-1 row-end-2 col-span-full">
          header
        </header>
        <StoreProvider>
          <main className="row-start-2 row-end-12 col-span-full">
            {children}
          </main>
        </StoreProvider>
        <footer className="p-3 row-start-12 row-end-13 col-span-full">
          footer
        </footer>
      </body>
    </html>
  );
}
