# Generated by Django 5.0.3 on 2024-03-26 00:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('balance', models.IntegerField()),
                ('transactions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
