# Generated by Django 5.0.3 on 2024-04-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id_alter_account_transactions'),
        ('users', '0004_alter_bankuser_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.bankuser'),
        ),
    ]
